disabled_rules:
 - trailing_whitespace
 - large_tuple
 - weak_delegate
 
opt_in_rules:
 - force_unwrapping

line_length: 
  warning: 160
  error: 200

identifier_name:
  min_length: 2
  max_length: 50
